apiVersion: v1
kind: Secret
metadata:
  name: n8n-credentials
  namespace: n8n-prod
type: Opaque
stringData:
  POSTGRES_USER: "n8nuser"
  POSTGRES_PASSWORD: "XXX"
  POSTGRES_DB: "n8n"
  REDIS_PASSWORD: "XXX"
  N8N_ENCRYPTION_KEY: "XXXYYYZZZ"
  SENDGRID_API_KEY: "XX.YYYZZZ"
