apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      volumes:
        - name: n8n-storage
          persistentVolumeClaim:
            claimName: n8n-pvc
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
        - name: wait-for-redis
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            # --- Database Configuration ---
            - name: DB_TYPE
              value: "postgresdb"
            - name: DB_POSTGRESDB_HOST
              value: "postgres"
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: n8n-credentials
                  key: POSTGRES_DB
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-credentials
                  key: POSTGRES_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-credentials
                  key: POSTGRES_PASSWORD
            
            # --- Queue Mode Configuration ---
            - name: EXECUTIONS_MODE
              value: "queue"
            - name: QUEUE_BULL_REDIS_HOST
              value: "redis"
            - name: QUEUE_BULL_REDIS_PORT
              value: "6379"
            - name: QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-credentials
                  key: REDIS_PASSWORD
            
            # --- n8n Core Configuration ---
            - name: N8N_HOST
              value: "123.456.789.10"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "http"
            - name: WEBHOOK_URL
              value: "http://123.456.789.10:30000/"
            - name: N8N_SECURE_COOKIE
              value: "false"
            
            # --- Security & Encryption ---
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-credentials
                  key: N8N_ENCRYPTION_KEY
            
            # --- Email Configuration ---
            - name: N8N_EMAIL_MODE
              value: "smtp"
            - name: N8N_SMTP_HOST
              value: "smtp.sendgrid.net"
            - name: N8N_SMTP_PORT
              value: "587"
            - name: N8N_SMTP_USER
              value: "apikey"
            - name: N8N_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: n8n-credentials
                  key: SENDGRID_API_KEY
            - name: N8N_SMTP_SENDER
              value: "Notifications <info@example.com>"
            
            # --- General Settings ---
            - name: GENERIC_TIMEZONE
              value: "Europe/Paris"
            - name: NODE_ENV
              value: "production"
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "false"
            - name: N8N_METRICS
              value: "true"
            - name: N8N_LOG_LEVEL
              value: "info"
            
          volumeMounts:
            - name: n8n-storage
              mountPath: /home/node/.n8n
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n-prod
spec:
  selector:
    app: n8n
  ports:
    - port: 5678
      targetPort: 5678
